# Generated by Django 3.0.5 on 2020-04-05 02:45

from django.db import migrations
import fontawesome.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200403_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='icon',
            field=fontawesome.fields.IconField(blank=True, max_length=60),
        ),
    ]
