# Generated by Django 3.0.5 on 2020-04-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_member_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='category',
            field=models.CharField(choices=[('PLUMBING', 'Plumbing'), ('ELECTRICAL', 'Electrical'), ('MASONRY', 'Masonry'), ('FRAMING', 'Framing'), ('ROOFING', 'Roofing'), ('HOMEOWNER', 'Homeowner')], default='misc', max_length=30),
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('SUPPLIER', 'Supplier'), ('SUB-CONTRACTOR', 'Sub-Contractor'), ('HOMEOWNER', 'Homeowner')], default='misc', max_length=30),
        ),
    ]
