# Generated by Django 3.0.4 on 2020-03-24 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FloorPlan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.RemoveField(
            model_name='task',
            name='responsibilty',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='role',
        ),
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('PLUMBING', 'Plumbing'), ('ELECTRICAL', 'Electrical'), ('MASONRY', 'Masonry'), ('FRAMING', 'Framing'), ('ROOFING', 'Roofing')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='task',
            name='assignee',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='FloorPlan.TeamMember'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='company',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='FloorPlan.TeamMember'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('SUPPLIER', 'Supplier'), ('SUB-CONTRACTOR', 'Sub-Contractor'), ('HOMEOWNER', 'Homeowner')], max_length=30)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='FloorPlan.TeamMember')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='role',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='FloorPlan.Role'),
        ),
    ]
