# Generated by Django 3.0.4 on 2020-03-23 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FloorPlan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmanager',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='projectmanager',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
        migrations.RenameModel(
            old_name='Contractor',
            new_name='TeamMember',
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.CharField(max_length=400)),
                ('lot_number', models.CharField(blank=True, max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='FloorPlan.ProjectManager')),
            ],
        ),
        migrations.CreateModel(
            name='Catergory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('task', models.TextField(max_length=255)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='FloorPlan.TeamMember')),
            ],
        ),
    ]
