# Generated by Django 3.0.4 on 2020-03-23 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FloorPlan', '0002_auto_20200323_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='task',
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField(max_length=300)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='FloorPlan.Category')),
                ('responsibilty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned', to='FloorPlan.TeamMember')),
            ],
        ),
    ]
