# Generated by Django 3.0.4 on 2020-03-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FloorPlan', '0002_auto_20200324_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
