# Generated by Django 3.0.4 on 2020-04-02 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FloorPlan', '0003_auto_20200402_1550'),
        ('FloorPlan', '0003_auto_20200402_1402'),
    ]

    operations = [
    ]
