# Generated by Django 3.0.4 on 2020-03-24 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FloorPlan', '0003_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='team_members',
            field=models.ManyToManyField(to='FloorPlan.TeamMember'),
        ),
    ]
