# Generated by Django 3.0.4 on 2020-04-02 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FloorPlan', '0004_merge_20200402_1603'),
        ('FloorPlan', '0004_merge_20200402_1602'),
    ]

    operations = [
    ]
