# Generated by Django 3.0.4 on 2020-03-25 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FloorPlan', '0005_task_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(default='project', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='FloorPlan.Project'),
        ),
    ]
