# Generated by Django 3.0.4 on 2020-03-25 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FloorPlan', '0005_task_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='project',
        ),
    ]
