# Generated by Django 3.0.4 on 2020-04-03 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FloorPlan', '0005_auto_20200403_0928'),
        ('FloorPlan', '0005_merge_20200402_1612'),
    ]

    operations = [
    ]
