# Generated by Django 3.0.4 on 2020-04-03 13:57

from django.db import migrations

def add_categories(apps, schema_editor):
    Category = apps.get_model('FloorPlan', 'Category')
    for category in Category.objects.all():
        category.category = category.category
        category.save()

class Migration(migrations.Migration):

    dependencies = [
        ('FloorPlan', '0005_auto_20200403_0928'),
    ]

    operations = [
        migrations.RunPython(add_categories), 
    ]
