# Generated by Django 3.0.4 on 2020-03-25 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FloorPlan', '0006_auto_20200325_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(default='project', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='FloorPlan.Project'),
        ),
    ]
