# Generated by Django 3.0.4 on 2020-04-03 19:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FloorPlan', '0006_auto_20200403_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_team',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
