# Generated by Django 3.0.4 on 2020-04-03 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FloorPlan', '0006_auto_20200403_0957'),
        ('FloorPlan', '0006_merge_20200403_0944'),
    ]

    operations = [
    ]
