# Generated by Django 3.0.4 on 2020-04-04 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FloorPlan', '0007_project_project_team'),
        ('FloorPlan', '0007_merge_20200403_0958'),
    ]

    operations = [
    ]
