# Generated by Django 3.0.4 on 2020-03-26 17:29

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('FloorPlan', '0007_auto_20200326_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmanager',
            name='phone',
            field=phone_field.models.PhoneField(max_length=11),
        ),
    ]
