# Generated by Django 3.0.5 on 2020-04-04 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FloorPlan', '0012_auto_20200404_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_categories',
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='project',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='projectcategories', to='FloorPlan.Project'),
        ),
    ]
