# Generated by Django 3.0.4 on 2020-03-27 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FloorPlan', '0012_task_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('PLUMBING', 'Plumbing'), ('ELECTRICAL', 'Electrical'), ('MASONRY', 'Masonry'), ('FRAMING', 'Framing'), ('ROOFING', 'Roofing'), ('HOMEOWNER', 'Homeowner')], default='misc', max_length=30),
        ),
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(choices=[('PROJECT-MANAGER', 'Project-Manager'), ('SUPPLIER', 'Supplier'), ('SUB-CONTRACTOR', 'Sub-Contractor'), ('HOMEOWNER', 'Homeowner')], max_length=30),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='FloorPlan.Project'),
        ),
    ]
