# Generated by Django 3.0.5 on 2020-04-04 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FloorPlan', '0013_auto_20200404_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='custom_category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='customtasks', to='FloorPlan.ProjectCategory'),
        ),
        migrations.CreateModel(
            name='ProjectCategoryTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField(max_length=255)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('assignee', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='projectcategorytasks', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectcategorytasks', to='FloorPlan.ProjectCategory')),
                ('project', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='projectcategoriestasks', to='FloorPlan.Project')),
            ],
        ),
    ]
