# Generated by Django 3.0.5 on 2020-04-04 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FloorPlan', '0014_auto_20200404_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='custom_category',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customtasks', to='FloorPlan.ProjectCategory'),
        ),
    ]
