# Generated by Django 3.0.4 on 2020-03-28 16:13

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('FloorPlan', '0015_auto_20200327_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmanager',
            name='phone',
            field=phone_field.models.PhoneField(max_length=20),
        ),
    ]
