# Generated by Django 3.0.4 on 2020-03-28 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FloorPlan', '0015_auto_20200327_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='member',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='team_member',
        ),
        migrations.RemoveConstraint(
            model_name='category',
            name='unique_team',
        ),
        migrations.RemoveField(
            model_name='category',
            name='category',
        ),
        migrations.RemoveField(
            model_name='category',
            name='member',
        ),
        migrations.RemoveField(
            model_name='task',
            name='role',
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='team_members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ProjectManager',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='TeamMember',
        ),
    ]
