# Generated by Django 3.0.5 on 2020-04-05 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FloorPlan', '0016_auto_20200404_1902'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['due_date']},
        ),
    ]
