# Generated by Django 3.0.5 on 2020-04-05 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FloorPlan', '0017_auto_20200404_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='custom_category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customtasks', to='FloorPlan.ProjectCategory'),
        ),
    ]
