# Generated by Django 3.0.4 on 2020-03-30 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FloorPlan', '0021_auto_20200329_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='category',
        ),
    ]
