# Generated by Django 3.0.4 on 2020-03-30 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FloorPlan', '0022_remove_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='project',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='FloorPlan.Project'),
        ),
    ]
